<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>AtomUI.Labs.Controls.ScrollMarker.Performance</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless" />
        <PackageReference Include="Avalonia.Skia" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/AtomUI.Labs.Controls.ScrollMarker/AtomUI.Labs.Controls.ScrollMarker.csproj" />
    </ItemGroup>
</Project>
